name: Publish package to GitHub Packages
on:
  release:
    types: [created]
	
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -c release
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
	  	with:
            name: solita
            path: .build/release/SolitaCLI
    - name: Checksum
      run: shasum -a 256 .build/release/SolitaCLI >> checksum
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
	  	with:
             name: checksum
             path: checksum